// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVfXPtPX01r7lBRbRq8isR8Y6Y3oswi6M',
    appId: '1:1018909446820:web:57a4adec95df4acbd90c31',
    messagingSenderId: '1018909446820',
    projectId: 'chats-28d6f',
    authDomain: 'chats-28d6f.firebaseapp.com',
    storageBucket: 'chats-28d6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJWN0CiPgMhLlY1BEwW2sNqrLGTIJxmPs',
    appId: '1:1018909446820:android:42f139496d2965e3d90c31',
    messagingSenderId: '1018909446820',
    projectId: 'chats-28d6f',
    storageBucket: 'chats-28d6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB33Y8PZcEhhvEk6lEOl_o6WlSChAbIHxc',
    appId: '1:1018909446820:ios:bc531a72e82e27bdd90c31',
    messagingSenderId: '1018909446820',
    projectId: 'chats-28d6f',
    storageBucket: 'chats-28d6f.appspot.com',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB33Y8PZcEhhvEk6lEOl_o6WlSChAbIHxc',
    appId: '1:1018909446820:ios:49bd2eaf2007bfecd90c31',
    messagingSenderId: '1018909446820',
    projectId: 'chats-28d6f',
    storageBucket: 'chats-28d6f.appspot.com',
    iosBundleId: 'com.example.chats.RunnerTests',
  );
}
